name: Pytest

on: 
  pull_request_target:
    paths:
      - 'src/mountainash_data/**'          
  workflow_dispatch:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ "3.12"] #, "3.8", "3.9", "3.10","3.11",]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Current Branch
      - name: Get branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})" >> $GITHUB_ENV

      ###### MtAsh DEPENDENCIES ######

      - name: Verify Token is set 
        shell: bash
        env:
          TOKEN: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "TOKEN is unset or set to the empty string"
          else
            echo "TOKEN is set"
          fi

          echo "Using BRANCH_NAME: $BRANCH_NAME"


      - name: Checkout dependencies
        shell: bash
        env:
          TOKEN: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          REPOSITORIES: mountainash-data mountainash-constants mountainash-auth-settings mountainash-settings mountainash-utils-dataclasses mountainash-utils-files mountainash-utils-os mountainash-utils-ssh
        run: |
          set -x  # Enable verbose output
          IFS=' ' read -r -a REPO_ARRAY <<< "$REPOSITORIES"
          for REPO in "${REPO_ARRAY[@]}"; do
            echo "Checking out $REPO"
            BRANCH_EXISTS=$(git ls-remote --heads https://x-access-token:$TOKEN@github.com/mountainash-io/$REPO.git $BRANCH_NAME | wc -l)
            if [ $BRANCH_EXISTS -eq 0 ]; then
              BRANCH="main"
            else
              BRANCH=$BRANCH_NAME
            fi
            echo "Attempting to checkout branch: $BRANCH on repo: $REPO"
            git clone --depth 1 -b $BRANCH https://x-access-token:$TOKEN@github.com/mountainash-io/$REPO.git temp/$REPO || {
              echo "Failed to checkout $REPO, retrying..."
              sleep 5
              git clone --depth 1 -b $BRANCH https://x-access-token:$TOKEN@github.com/mountainash-io/$REPO.git temp/$REPO || echo "Failed to checkout $REPO on second attempt"
            }
          done


      # # mountainash-auth-settings
      # - name: Checkout matching branch - mountainash-auth-settings
      #   id: check_branch_auth_settings
      #   continue-on-error: true
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-auth-settings
      #     ref: ${{ env.BRANCH_NAME }}
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-auth-settings
      #     fetch-depth: 1

      # - name: Checkout main branch - mountainash-auth-settings
      #   if: steps.check_branch_auth_settings.outcome == 'failure'
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-auth-settings
      #     ref: main
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-auth-settings
      #     fetch-depth: 1

      # # mountainash-constants
      # - name: Checkout matching branch - mountainash-constants
      #   id: check_branch_constants
      #   continue-on-error: true
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-constants
      #     ref: ${{ env.BRANCH_NAME }}
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-constants
      #     fetch-depth: 1

      # - name: Checkout main branch - mountainash-constants
      #   if: steps.check_branch_constants.outcome == 'failure'
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-constants
      #     ref: main
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-constants
      #     fetch-depth: 1


      # # mountainash-settings
      # - name: Checkout matching branch - mountainash-settings
      #   id: check_branch_settings
      #   continue-on-error: true
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-settings
      #     ref: ${{ env.BRANCH_NAME }}
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-settings
      #     fetch-depth: 1

      # - name: Checkout main branch - mountainash-settings
      #   if: steps.check_branch_settings.outcome == 'failure'
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-settings
      #     ref: main
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-settings
      #     fetch-depth: 1


      # ###### MtAsh UTILS DEPENDENCIES ######

      # # mountainash-utils-dataclasses
      # - name: Checkout matching branch - mountainash-utils-dataclasses
      #   id: check_branch_utils_dataclasses
      #   continue-on-error: true
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-utils-dataclasses
      #     ref: ${{ env.BRANCH_NAME }}
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-utils-dataclasses
      #     fetch-depth: 1

      # - name: Checkout main branch - mountainash-utils-dataclasses
      #   if: steps.check_branch_utils_dataclasses.outcome == 'failure'
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-utils-dataclasses
      #     ref: main
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-utils-dataclasses
      #     fetch-depth: 1


      # # mountainash-utils-files
      # - name: Checkout matching branch - mountainash-utils-files
      #   id: check_branch_utils_files
      #   continue-on-error: true
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-utils-files
      #     ref: ${{ env.BRANCH_NAME }}
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-utils-files
      #     fetch-depth: 1

      # - name: Checkout main branch - mountainash-utils-files
      #   if: steps.check_branch_utils_files.outcome == 'failure'
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-utils-files
      #     ref: main
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-utils-files
      #     fetch-depth: 1

      # # mountainash-utils-os
      # - name: Checkout matching branch - mountainash-utils-os
      #   id: check_branch_utils_os
      #   continue-on-error: true
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-utils-os
      #     ref: ${{ env.BRANCH_NAME }}
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-utils-os
      #     fetch-depth: 1

      # - name: Checkout main branch - mountainash-utils-os
      #   if: steps.check_branch_utils_os.outcome == 'failure'
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-utils-os
      #     ref: main
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-utils-os
      #     fetch-depth: 1


      # # mountainash-utils-ssh
      # - name: Checkout matching branch - mountainash-utils-ssh
      #   id: check_branch_utils_ssh
      #   continue-on-error: true
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-utils-ssh
      #     ref: ${{ env.BRANCH_NAME }}
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-utils-ssh
      #     fetch-depth: 1

      # - name: Checkout main branch - mountainash-utils-ssh
      #   if: steps.check_branch_utils_ssh.outcome == 'failure'
      #   uses: actions/checkout@v4
      #   with:
      #     repository: mountainash-io/mountainash-utils-ssh
      #     ref: main
      #     token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
      #     path: temp/mountainash-utils-ssh
      #     fetch-depth: 1
            

      # Install Hatch
      - name: Install Hatch
        run: pip install hatch

      - name: Create virtual environment
        run: hatch env create test_github

      #Run Pytest
      - name: Run tests
        run: hatch run test_github:test

      # Run Coverage
      - name: Run Coverage Tests
        run: hatch run test_github:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: mountainash-io/mountainash-data